---
title: "Coho CWT FRAM & MSM Analysis"
author: "Dan.Auerbach@dfw.wa.gov, Angelika.Hagen-Breaux@dfw.wa.gov, carrie_cook-tabor@fws.gov"
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
output: 
  bookdown::html_document2:
    fig_caption: yes
    theme: cerulean
    toc: yes
    toc_depth: 3
    toc_float: yes
    code_folding: hide
---

```{r setup, results = FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, results = FALSE, warning = FALSE, message = FALSE, fig.width = 9, fig.height = 9)

library("tidyverse")
library("gt")
library("odbc"); library("DBI")
#library("ggridges")

dir_proj <- "T:/DFW-Salmon Mgmt Modeling Team - General/Southern Fund Projects/Coho FRAM MSM CWT analysis/"

fp <- list(
  db_msm = "T:/DFW-Salmon Mgmt Modeling Team - General/Southern Fund Projects/Coho FRAM MSM CWT analysis/MSMDB/MSM_98-2020- SF2019.mdb",
  rmis_recs = file.path(dir_proj, "rmis_coho_recoveries_86_2020.rds"),
  rmis_rel = file.path(dir_proj, "rmis_coho_releases_for_rec_86_2020.rds"),
  rmis_rec_rel = file.path(dir_proj, "rmis_coho_rec_rel_86_2020.rds")
  )

rmis_rr <- readRDS(fp$rmis_rec_rel) |> 
  filter(!is.na(release_location_state)) #drop 3 recent

```

# Summary

# Data

## RMIS wrangling

```{r read_in_rmis_recoveries, eval=FALSE}
dir_rmis_recs <- "T:/DFW-Salmon Mgmt Modeling Team - General/Southern Fund Projects/Coho FRAM MSM CWT analysis/ERAnalysis/RMISRecoveries/"

focal_cols_recs <- c("recovery_id", "tag_code", "run_year", "recovery_location_code", "recovery_location_name", "fishery", "gear", "estimated_number")

# rmis_recs <- purrr::map_dfr(
#   list.files(dir_rmis_recs, full.names = T)
#   ,
#   ~readr::read_csv(.x, col_select = all_of(focal_cols_recs))
#   )
# 
# saveRDS(rmis_recs, "T:/DFW-Salmon Mgmt Modeling Team - General/Southern Fund Projects/Coho FRAM MSM CWT analysis/rmis_coho_recoveries_86_2020.rds")

```

```{r get_releases_by_tag_code, eval=FALSE}
rmis_recs |> 
  mutate(year_set = if_else(run_year <= 1992, "86-92", "93-20")) |> 
  #distinct(year_set, tag_code) |> split(~year_set) |> 
  distinct(tag_code) |> rownames_to_column(var = "id") |> 
  mutate(
    id = as.numeric(id), 
    block = cut(id, breaks = c(seq(0,20000,by=2000))),
    block = letters[as.integer(block)]
    ) |> #count(block)
  split(~block) |> 
  writexl::write_xlsx("T:/DFW-Salmon Mgmt Modeling Team - General/Southern Fund Projects/Coho FRAM MSM CWT analysis/ERAnalysis/tag_codes_by_block.xlsx")

f <- "T:/DFW-Salmon Mgmt Modeling Team - General/Southern Fund Projects/Coho FRAM MSM CWT analysis/ERAnalysis/tag_codes_by_block.xlsx"

#readxl::read_excel(f, sheet = "a") |> pluck("tag_code") |> writeLines("clipboard")
#readxl::read_excel(f, sheet = "b") |> pluck("tag_code") |> writeLines("clipboard")
#readxl::read_excel(f, sheet = "c") |> pluck("tag_code") |> writeLines("clipboard")
#readxl::read_excel(f, sheet = "d") |> pluck("tag_code") |> writeLines("clipboard")
#readxl::read_excel(f, sheet = "e") |> pluck("tag_code") |> writeLines("clipboard")
#readxl::read_excel(f, sheet = "f") |> pluck("tag_code") |> writeLines("clipboard")
#readxl::read_excel(f, sheet = "g") |> pluck("tag_code") |> writeLines("clipboard")

focal_cols_rel <- c("tag_code_or_release_id", "brood_year", "release_location_code", "hatchery_location_code", "stock_location_code", "release_location_name", "hatchery_location_name", "stock_location_name", "release_location_state", "release_location_rmis_region", "release_location_rmis_basin", "cwt_1st_mark", "cwt_1st_mark_count", "cwt_2nd_mark", "cwt_2nd_mark_count")

rmis_rel <- map_df(
  c(
  "https://www.rmis.org/reports/CSV13497.txt",
  "https://www.rmis.org/reports/CSV13656.txt",
  "https://www.rmis.org/reports/CSV13738.txt",
  "https://www.rmis.org/reports/CSV13814.txt",
  "https://www.rmis.org/reports/CSV13854.txt",
  "https://www.rmis.org/reports/CSV14030.txt",
  "https://www.rmis.org/reports/CSV14116.txt"
  ),
  ~read_csv(.x, col_select = all_of(focal_cols_rel)) |> 
    mutate(
      cwt_1st_mark = as.character(cwt_1st_mark),
      cwt_2nd_mark = as.character(cwt_2nd_mark)
      )
  )


saveRDS(rmis_rel, "T:/DFW-Salmon Mgmt Modeling Team - General/Southern Fund Projects/Coho FRAM MSM CWT analysis/rmis_coho_releases_for_rec_86_2020.rds")

```

```{r build_rec_rel, eval=FALSE}

left_join(
  readRDS(fp$rmis_recs) |> 
    mutate(
      rec_loc_1 = str_sub(recovery_location_code,1,1),
      rec_loc_2 = str_sub(recovery_location_code,2,2),
      f_type = case_when(
        between(fishery, 10, 19) ~ "troll",
        between(fishery, 20, 39) ~ "net",
        between(fishery, 40, 49) ~ "sport",
        between(fishery, 50, 59) ~ "escp"
      )
    )
  ,
  readRDS(fp$rmis_rel) |> select(-contains("n_code")),
  by = c("tag_code" = "tag_code_or_release_id")
  ) |> 
  saveRDS(file.path(dir_proj, "rmis_coho_rec_rel_86_2020.rds"))

```

## mapping

```{r}
#86-91, 92-97, 98-2020

db <- "C:/Users/auerbdaa/Downloads/MSM_98-2020- SF2019_cmpct.mdb"
db_con <- DBI::dbConnect(
  drv = odbc::odbc(),
  .connection_string = paste0("Driver={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=", db, ";")
  )

msm_tbl_names <- c("Edit_Distinct")

msm_tbl <- map(set_names(msm_tbl_names), ~collect(tbl(db_con, .x)))

msm_tbl$Edit_Distinct

DBI::dbDisconnect(db_con)

```

Starting to rough out an R version of MSM mapping...

```{r}
#Edit_Distinct.Gear == first character of RMIS fishery
#approx logic: check match of Edit_Distinct.PSC_Code against corresponding Num_Chars of recovery_location_code
#Edit_Distinct.Fishery_Number is a PSC fishery code, which then needs further mapping to FRAM

msm_tbl$Edit_Distinct |> count(Num_Chars)


split(msm_tbl$Edit_Distinct, msm_tbl$Edit_Distinct$Num_Chars)[1:2] |> 
  map(
    function(df){
      nc = df$Num_Chars[1]
      rmis_recs |> 
        mutate(
          PSC_Code = str_sub(recovery_location_code, 1, nc)
        ) |> 
        left_join(df, by = "PSC_Code")
    }
  )
  


```


# Recovery patterns

## Rec by release state

totals by year, needs further stratification

```{r rec_by_rel_state}
rmis_rr |> 
  count(run_year, release_location_state) |> #release_location_rmis_region
  ggplot(aes(run_year, n, fill = release_location_state)) + 
  geom_col(show.legend = F) +
  facet_wrap(~release_location_state, ncol = 1, scales = "free")

  #filter(as.numeric(cwt_1st_mark) < 5000) |> 
```

## Rec release region, all

```{r}
#tidy objects up
regions_col_riv <- c("CECR", "CRGN", "LOCR", "UPCR")
regions_ps <- c("SPS", "MPS", "NPS", "HOOD", "JUAN", "SKAG", "NOWA")
regions_wa_cst <- c("NWC", "GRAY", "WAGN", "WILP")

rmis_rr |> 
  count(run_year, f_type = f_type == "escp", release_location_rmis_region) |>
  filter(!is.na(f_type)) |> 
  ggplot(aes(run_year, release_location_rmis_region, fill = n)) + 
  geom_raster(show.legend = T) +
  wacolors::scale_fill_wa_c("gorge", reverse = T) +
  facet_wrap(~f_type, ncol = 1, scales = "free")

#raster n-recs region by year
rmis_rr |> 
  filter(f_type %in% c("net", "troll", "sport")) |> 
  count(run_year, f_type, release_location_rmis_region) |>
  ggplot(aes(run_year, release_location_rmis_region, fill = n)) + 
  geom_raster(show.legend = T) +
  wacolors::scale_fill_wa_c("gorge", reverse = T) +
  facet_wrap(~f_type, ncol = 1, scales = "free")

#lines n-recs region (line color) by year
rmis_rr |> 
  filter(f_type %in% c("net", "troll", "sport")) |> 
  count(run_year, f_type, release_location_rmis_region) |>
  ggplot(aes(run_year, n, color = release_location_rmis_region)) + 
  geom_line(show.legend = T) +
  #wacolors::scale_fill_wa_d("gorge", reverse = T) +
  facet_wrap(~f_type, ncol = 1, scales = "free")

#split by ps release regions
rmis_rr |> 
  filter(f_type %in% c("net", "troll", "sport")) |> 
  count(run_year, f_type, release_location_rmis_region) |>
  filter(release_location_rmis_region %in% regions_ps) |> 
  ggplot(aes(run_year, n, color = release_location_rmis_region)) + 
  geom_line(show.legend = T) +
  wacolors::scale_fill_wa_d("rainier", reverse = T) +
  facet_wrap(~f_type, ncol = 1)

#aggregate by ps_release region, f_type color
rmis_rr |> 
  filter(
    f_type %in% c("net", "troll", "sport"),
    release_location_rmis_region %in% regions_ps
    ) |> 
  count(run_year, f_type) |>
  ggplot(aes(run_year, n, color = f_type)) + 
  geom_line(show.legend = T) +
  facet_wrap(~f_type, ncol = 1)


# rmis_rr |> 
#   filter(f_type %in% c("net", "troll", "sport")) |> 
#   group_by(run_year, f_type, release_location_rmis_region) |>
#   summarise(n = n(), est_num = sum(estimated_number, na.rm = T), .groups = "drop") |> 
#   #group_by(f_type) |> 
#   group_by(release_location_rmis_region) |> 
#   slice_max(order_by = n, n = 1) |> 
#   arrange(desc(n)) |> print(n = 50)

#comparing time periods of fishery recoveries by rel_region
rmis_rr |> 
  filter(
    between(run_year, 1986, 2019),
    f_type %in% c("net", "troll", "sport")
    ) |> 
  mutate(
    year_block = case_when(
      between(run_year, 1986, 1992) ~ "86-92",
      between(run_year, 1993, 2009) ~ "93-09",
      between(run_year, 2010, 2019) ~ "10-19"
      ) |> factor(levels = c("86-92", "93-09", "10-19")),
    ) |> 
  group_by(year_block, f_type, release_location_rmis_region) |>
  summarise(n = n(), est_num = sum(estimated_number, na.rm = T), .groups = "drop") |> 
  filter(year_block != "93-09") |> 
  ggplot(aes(release_location_rmis_region, n, fill = year_block)) +
  geom_col(position = position_dodge()) +
  facet_wrap(~f_type, scales = "free", ncol = 1)


#comparing time periods of recoveries in fisheries, excluding ColR releases
rmis_rr |> 
  filter(
    between(run_year, 1986, 2019),
    f_type %in% c("net", "troll", "sport"),
    !(release_location_rmis_region %in% regions_col_riv)
    ) |> 
  mutate(
    year_block = case_when(
      between(run_year, 1986, 1992) ~ "86-92",
      between(run_year, 1993, 2009) ~ "93-09",
      between(run_year, 2010, 2019) ~ "10-19"
      ) |> factor(levels = c("86-92", "93-09", "10-19")),
    ) |> 
  group_by(year_block, release_location_state) |>
  summarise(n = n(), est_num = sum(estimated_number, na.rm = T), .groups = "drop") |> 
  filter(year_block != "93-09", release_location_state %in% c("BC", "OR", "WA")) |> 
  ggplot(aes(release_location_state, n, fill = year_block)) +
  geom_col(position = position_dodge())

#drill down to examine just Fraser R releases
#very little to work with in recent years...
rmis_rr |> 
  filter(
    between(run_year, 1986, 2019),
    f_type %in% c("net", "troll", "sport"),
    release_location_rmis_region == "FRTH"
    ) |> 
  mutate(
    year_block = case_when(
      between(run_year, 1986, 1992) ~ "86-92",
      between(run_year, 1993, 2009) ~ "93-09",
      between(run_year, 2010, 2019) ~ "10-19"
      ) |> factor(levels = c("86-92", "93-09", "10-19")),
    ) |> 
  group_by(year_block, release_location_rmis_basin) |>
  summarise(n = n(), est_num = sum(estimated_number, na.rm = T), .groups = "drop") |> 
  ggplot(aes(release_location_rmis_basin, n, fill = year_block)) +
  geom_col(position = position_dodge())

rmis_rr |> 
  filter(release_location_rmis_basin == "LOFR", !is.na(f_type)) |> 
  count(run_year, f_type) |> 
  ggplot(aes(run_year, n, fill = f_type)) +
  geom_col(position = position_dodge())

rmis_rr |> 
  filter(release_location_rmis_basin == "LOFR", f_type == "sport") |> 
  count(run_year, rec_loc_1) |> 
  ggplot(aes(run_year, n, fill = rec_loc_1)) +
  geom_col(position = position_dodge())


#looking for release region with adequate recoveries both time blocks
#focus on fishery recoveries assuming that escp recs probably ok if fishery ok
rmis_rr |> 
  filter(
    between(run_year, 1986, 2019),
    f_type %in% c("net", "troll", "sport"),
    ) |> 
  mutate(
    year_block = case_when(
      between(run_year, 1986, 1992) ~ "86-92",
      between(run_year, 1993, 2009) ~ "93-09",
      between(run_year, 2010, 2019) ~ "10-19"
      ) |> factor(levels = c("86-92", "93-09", "10-19")),
    ) |> 


```



## trial dummy

```{r}
#trial dummy example
mpdrec <- readxl::read_excel("T:/DFW-Salmon Mgmt Modeling Team - General/Southern Fund Projects/Coho FRAM MSM CWT analysis/MSMDB/MappedRecoveries.xlsx", sheet = "MappedRecoveries")

mpdrec |>
  ggplot(aes(RunYear)) +
  geom_bar()
#equivalently...
mpdrec |>
  count(RunYear) |> 
  ggplot(aes(RunYear, n)) +
  geom_col()


#all recoveries
mpdrec |>
  ggplot(aes(factor(RunYear), factor(PrNum))) +
  geom_bin2d()

#all non-escapement recoveries
mpdrec |>
  filter(MSMFishCode != 228) |> 
  ggplot(aes(factor(RunYear), factor(PrNum))) +
  geom_bin2d() +
  scale_fill_distiller(direction = 1)

```


## PR by year

## PR_MU by year


