---
title: "Comparing Coho FRAM and RMIS estimates of exploitation"
author: "Dan.Auerbach@dfw.wa.gov, Angelika.Hagen-Breaux@dfw.wa.gov, carrie_cook-tabor@fws.gov"
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
output: 
  bookdown::html_document2:
    fig_caption: yes
    theme: cerulean
    toc: yes
    toc_depth: 3
    toc_float: yes
    code_folding: hide
---

```{r setup, results = FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, results = FALSE, warning = FALSE, message = FALSE, fig.width = 9, fig.height = 9)

library("tidyverse")
library("gt")
library("patchwork")
library("odbc"); library("DBI")
theme_set(theme_light())

dir_proj <- "T:/DFW-Salmon Mgmt Modeling Team - General/Southern Fund Projects/Coho FRAM MSM CWT analysis"

fp <- list(
  #RMIS query dataset construction shown below
  rmis_recs = file.path(dir_proj, "rmis_coho_recoveries_86_2020.rds"),
  rmis_rel = file.path(dir_proj, "rmis_coho_releases_for_rec_86_2020.rds"),
  rmis_rec_rel = file.path(dir_proj, "rmis_coho_rec_rel_86_2020.rds"),
  
  mdb_pst = "O:/code/coho/fram_mdbs/PSC_CoTC_PostSeason_CohoFRAMDB_thru2020_021622.mdb",
  
  lu_stock = "lu_cct_MSM_Stock_CWT_20220711.csv",
  lu_fish = "lu_ahb_FishMap_20220808.csv"
  )

lu <- list(
  ##CCT queried releases, QAQC'd and assigned to PR and PR_MU
  ##these are assigned to FRAM marked wild StockIDs
  ##and are limited to tag_codes for marked releases
  cwt_stk = readr::read_csv(fp$lu_stock) |>
    mutate(tag_code = str_remove(CWT_Code, "'")) |> 
    select(tag_code, n_rel = Number_Released, Release_name, Hatchery_name, Stock_name, StockID) |> 
    filter(!is.na(StockID))
  ,
  ##AHB extended prior FRAM fishery mapping on RMIS recovery_location_code and fishery/gear
  ##various QAQC during earlier project phases
  ahb_fishmap = readr::read_csv(fp$lu_fish) |> 
    select(FisheryID, FisheryName, fishery_single = Gear, Num_Chars, PSC_Code) |>
    distinct(FisheryID, FisheryName, fishery_single, Num_Chars, PSC_Code)
  )

```

# Data

```{r included_fisheries}
#samp_catch_coef <- readxl::read_excel("C:/Users/auerbdaa/Downloads/fram_samp_fulla.xlsx", sheet = "fram_samp_fulla")
samp_catch_coef <- read_csv("C:/Users/auerbdaa/Downloads/fram_samp_fulla.csv") |> select(-1)

# samp_catch_coef |> filter(Source == "Xpansion") |> count(Action)
# 
# samp_catch_coef |> 
#   filter(Source == "Xpansion", (Action != "Remove  fishery" | is.na(Action))) |> 
#   distinct(FisheryID) |> paste() |> cat()
## note this appears to have been constructed after "pairing" Tr/NT
## below added back missing NT paired members

# #excluding:
# - freshwater sport (little/no sampling)
# - most terminal (stock comp presumed less varied; very uneven sampling)
# - others with little/no recent year catch and/or sampling
# included:
fishery_ids <- c(
  15, 17, 18, 19, 20, 21, 22, #CA/OR
  23, 33, 34, 35, 37, 38, 39, 40, 41, 42, 43, #B10/WA Ocn
  44, 47, 48, 50, 81, 83, 88, 91, 92, 93, 
  97, 98, 102, 106, 107, 110, 112, 115,
  118, 120, 122, 124, 125, 129, 136, 142, 144,
  152, 154, 156, 158, 160, 161, 162,
  171, 172, 174, 175, 178, 179, 182, 189, #BC
  194, 195, 196, 197, 198, #AK
  #NT members of Tr/NT pairs missing from fram_samp_fulla
  80, 82, 87, 96, 101, 109, 111, 119, 121, 123, 
  130, 132, 137, 139, 141, 143, 145, 153, 155, 157, 159
  )

#per AHB request to combine NT & Tr net fisheries
#dropping several NT of now dropped pairs: 130, 132, 137, 139, 146 
fishery_ids_paired <- c(
  80, 82, 87, 96, 101, 109, 111, 119, 121, 123, 
  #130, 132, 137, 139,
  141, 143,
  #145,
  153, 155, 157, 159
  )

##previously excluded from FRAM:
# fram_fishery_fw_spt <- c(
#   24, 27,28,29,30,31,46,51,54,58,59,60,61,62,65,66,67,70,73,
#   76,89,90,94,95,99,100,108,116,117,127,128,135,149,150,151,
#   163,164,165,166,169
#   )
##paralleled but non-FisheryID-based in RMIS: filter(!(f_type == "sport" & rlwtr == "F"))
```

## FRAM

```{r get_starting_fram_dataset}
fram <- list()

#Skagit, Sno, Quilcene, George Adams, Nisqually, Green, Quillayute, Quinault, Willapa, Columbia Early, Columbia Late, Fraser Lower, Fraser Upper
stock_ids <- c(20, 38, 48, 58, 68, 96, 134, 148, 164, 166, 176, 226, 230)

run_ids <- 34:44 #2010:2020

db_con <- DBI::dbConnect(
  drv = odbc::odbc(),
  .connection_string = paste0(
    "Driver={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=",
    fp$mdb_pst, ";")
  )

fram$fishery <- tbl(db_con, "Fishery") |> 
  filter(Species == "COHO") |> 
  select(FisheryID:FisheryTitle) |> 
  collect()

DBI::dbDisconnect(db_con)


fram$escp <- framr::read_coho_escp(fp$mdb_pst, runs = run_ids, stocks = stock_ids)

fram$mort <- framr::read_coho_mort(fp$mdb_pst, runs = run_ids, stocks = stock_ids)

```

## RMIS

These chunks preserve one-time operations to generate starting datasets from RMIS.

```{r read_in_rmis_recoveries, eval=FALSE}
dir_rmis_recs <- "T:/DFW-Salmon Mgmt Modeling Team - General/Southern Fund Projects/Coho FRAM MSM CWT analysis/ERAnalysis/RMISRecoveries/"

focal_cols_recs <- c(
  "recovery_id", "tag_code", "run_year", 
  "recovery_location_code", "recovery_location_name", 
  "fishery", "gear", "estimated_number", "recorded_mark",
  "catch_sample_id", "sample_type")

rmis_recs <- purrr::map_dfr(
  list.files(dir_rmis_recs, pattern = ".TXT", full.names = T)
  ,
  ~readr::read_csv(.x, col_select = all_of(focal_cols_recs)) |> 
    dplyr::mutate(recorded_mark = as.character(recorded_mark))
  )

#saveRDS(rmis_recs, "T:/DFW-Salmon Mgmt Modeling Team - General/Southern Fund Projects/Coho FRAM MSM CWT analysis/rmis_coho_recoveries_86_2020.rds")

```

```{r get_releases_by_tag_code, eval=FALSE}
rmis_recs |>
  distinct(tag_code) |> rownames_to_column(var = "id") |>
  mutate(
    id = as.numeric(id),
    block = cut(id, breaks = c(seq(0,20000,by=2000))),
    block = letters[as.integer(block)]
    ) |> #count(block)
  split(~block) |>
  writexl::write_xlsx("T:/DFW-Salmon Mgmt Modeling Team - General/Southern Fund Projects/Coho FRAM MSM CWT analysis/ERAnalysis/tag_codes_by_block.xlsx")

f <- "T:/DFW-Salmon Mgmt Modeling Team - General/Southern Fund Projects/Coho FRAM MSM CWT analysis/ERAnalysis/tag_codes_by_block.xlsx"

readxl::read_excel(f, sheet = "a") |> pluck("tag_code") |> writeLines("clipboard")
readxl::read_excel(f, sheet = "b") |> pluck("tag_code") |> writeLines("clipboard")
readxl::read_excel(f, sheet = "c") |> pluck("tag_code") |> writeLines("clipboard")
readxl::read_excel(f, sheet = "d") |> pluck("tag_code") |> writeLines("clipboard")
readxl::read_excel(f, sheet = "e") |> pluck("tag_code") |> writeLines("clipboard")
readxl::read_excel(f, sheet = "f") |> pluck("tag_code") |> writeLines("clipboard")
readxl::read_excel(f, sheet = "g") |> pluck("tag_code") |> writeLines("clipboard")

focal_cols_rel <- c(
  "tag_code_or_release_id", "brood_year",
  "release_location_code", "hatchery_location_code", "stock_location_code",
  "release_location_name", "hatchery_location_name", "stock_location_name",
  "release_location_state", "release_location_rmis_region", "release_location_rmis_basin",
  "cwt_1st_mark", "cwt_1st_mark_count", "cwt_2nd_mark", "cwt_2nd_mark_count"
  )

rmis_rel <- map_df(
  c(
  "https://www.rmis.org/reports/CSV13497.txt",
  "https://www.rmis.org/reports/CSV13656.txt",
  "https://www.rmis.org/reports/CSV13738.txt",
  "https://www.rmis.org/reports/CSV13814.txt",
  "https://www.rmis.org/reports/CSV13854.txt",
  "https://www.rmis.org/reports/CSV14030.txt",
  "https://www.rmis.org/reports/CSV14116.txt"
  ),
  ~read_csv(.x, col_select = all_of(focal_cols_rel)) |> 
    mutate(
      cwt_1st_mark = as.character(cwt_1st_mark),
      cwt_2nd_mark = as.character(cwt_2nd_mark)
      )
  )

#saveRDS(rmis_rel, "T:/DFW-Salmon Mgmt Modeling Team - General/Southern Fund Projects/Coho FRAM MSM CWT analysis/rmis_coho_releases_for_rec_86_2020.rds")

```

```{r join_rel_to_rec, eval=FALSE}
left_join(
  readRDS(fp$rmis_recs) |> 
    mutate(
      rlsp = str_sub(recovery_location_code, 1, 1),
      rlwtr = str_sub(recovery_location_code, 2, 2),
      rlsctr = str_sub(recovery_location_code, 3, 3),
      rlrgn = str_sub(recovery_location_code, 4, 5),
      rlarea = str_sub(recovery_location_code, 6, 9),
      rllocn = str_sub(recovery_location_code, 10, 16),
      rlsubl = str_sub(recovery_location_code, 17, 19),
      f_type = case_when(
        between(fishery, 10, 19) ~ "troll",
        between(fishery, 20, 39) ~ "net",
        between(fishery, 40, 49) ~ "sport",
        between(fishery, 50, 59) ~ "escp"
      )
    )
  ,
  readRDS(fp$rmis_rel) |> select(-contains("n_code")),
  by = c("tag_code" = "tag_code_or_release_id")
  ) |> #saveRDS(file.path(dir_proj, "rmis_coho_rec_rel_86_2020.rds"))

```

```{r rmis_rr}
#primary dataset, constructed and preserved in chunks below
rmis_rr <- readRDS(fp$rmis_rec_rel) |> 
  filter(!is.na(release_location_state)) |>  #drop 3 recent
  mutate(age = run_year - brood_year) |> 
  rowid_to_column("uid")

#adding missing Canadian escapements
rmis_rr <- bind_rows(
  rmis_rr,
  readxl::read_xlsx(
    file.path(dir_proj, "ERAnalysis/2022-02-23 StAD Escapement Report_Coho_EPAD.xlsx"),
    sheet = "Obs-Est-Exp"
    ) |>
    rowid_to_column(var = "uid") |> 
    mutate(
      uid = uid + last(rmis_rr$uid),
      age = `Recovery Year` - `Brood Year`,
      fishery = 50,
      f_type = "escp"
    ) |> 
    select(
      uid,
      tag_code = Tagcode, 
      recovery_location_code = `PSC Location Code`,
      recovery_location_name = `Recovery Site Name`,
      run_year = `Recovery Year`,
      brood_year = `Brood Year`,
      age,
      fishery, f_type,
      estimated_number = `Final Expanded`
    ) |> 
    filter(
      tag_code %in% unique(rmis_rr$tag_code),
      age == 3
    ) 
  )


#add CCT mapped StockIDs
rmis_rr <- rmis_rr |> left_join(lu$cwt_stk, by = c("tag_code"))

#add AHB mapped FisheryIDs
#cannot directly join on 'PSC_Code'...have to use the Num_Chars field
#but that means using many possible lengths of recovery_location_code
#brute force iterator over Num_chars + uid to allow recombination

#first declare temp object of only key fields
rmis_rr_ahb_map <- rmis_rr |> 
  select(uid, recovery_location_code, fishery) |> 
  mutate(fishery_single = floor(fishery/10)) 
#now overwrite as split-then-bind pattern on Num_Chars
#per AHB request, added explicit right string padding to specified string length
#even when actual strings in RMIS and LU are/use fewer char
rmis_rr_ahb_map <- map_df(
  sort(unique(lu$ahb_fishmap$Num_Chars)),
  ~inner_join(
    rmis_rr_ahb_map |> 
      mutate(PSC_Code = str_sub(recovery_location_code, 1, .x) |> str_pad(width = .x, side = "right"))
    ,
    lu$ahb_fishmap |> filter(Num_Chars == .x) |> 
      mutate(PSC_Code = str_pad(PSC_Code, width = .x, side = "right"))
    ,
    by = c("PSC_Code", "fishery_single")
  )
)

#some cases of same fishery from different n-chars being considered on same recovery_location_code
#some cases initially from simple row duplication in lookup, now fixed on read-in
overmapped <- rmis_rr_ahb_map |> count(uid) |> filter(n>1) |> select(uid)

#now rejoin to full dataset, after making FisheryID distinct per UID
rmis_rr <- left_join(
  rmis_rr, 
  #split out multiple-mapped, make distinct per UID and rebind
  bind_rows(
    anti_join(rmis_rr_ahb_map, overmapped, by = "uid") |> 
      select(uid, FisheryID)
    ,
    semi_join(rmis_rr_ahb_map, overmapped, by = "uid") |> 
      group_by(uid) |> 
      slice_max(Num_Chars, n = 1, with_ties = F) |> 
      ungroup() |> 
      select(uid, FisheryID) #|> count(uid) |> filter(n>1)
  )
  ,
  by = "uid") |> 
  left_join(fram$fishery, by = "FisheryID")

rm(rmis_rr_ahb_map, overmapped)

```

# Exploitation calculations

```{r er_objects_included_fisheries}

samp_catch_coef_vals <- samp_catch_coef |>
  filter(Source == "Xpansion", (Action != "Remove  fishery" | is.na(Action))) |>
  select(FisheryID, `2010`:`2019`) |> 
  pivot_longer(cols = -FisheryID, names_to = "run_year", values_to = "coef") |> 
  mutate(run_year = as.numeric(run_year))


er_fram <- full_join(
  fram$mort |>
    mutate(
      run_year = as.integer(RunYear), RunYear = NULL,
      FisheryID = if_else(FisheryID %in% fishery_ids_paired, FisheryID+1, as.double(FisheryID)),
      FisheryName = if_else(FisheryID %in% c(fishery_ids_paired, fishery_ids_paired+1),
                            str_sub(FisheryName, 1,8), FisheryName)
    ) |> 
    filter(FisheryID %in% fishery_ids) |> 
    group_by(run_year, StockID, StockLongName, FisheryID, FisheryName) |> 
    summarise(
      across(c(LandedCatch, MSFLandedCatch), sum), #sum over timesteps
      fram_lnd_yr_fsh = LandedCatch + MSFLandedCatch,
      .groups = "drop") |> 
    ##excluding fishery-year levels for still-included fisheries
    ##resulting ERs for a stock then vary between years in terms of which fisheries contribute
    ##but should parallel RMIS
    #     anti_join(
    #       samp_catch_coef_vals |> filter(coef == 0),
    #       by = c("FisheryID", "run_year")
    #     ) |> 
    left_join(
      samp_catch_coef_vals |> filter(coef == 0),
      by = c("FisheryID", "run_year")
    ) |> 
    mutate(fram_lnd_yr_fsh = if_else(!is.na(coef), coef * fram_lnd_yr_fsh, fram_lnd_yr_fsh)) |> 
    group_by(run_year, StockID, StockLongName) |> 
    mutate(
      LandedCatch = NULL, MSFLandedCatch = NULL,
      fram_lnd_yr_tot = sum(fram_lnd_yr_fsh)
    ) |> 
    ungroup()
  ,
  fram$escp |> 
    rename(fram_escp = escp) |> 
    mutate(run_year = as.integer(RunYear), RunYear = NULL) |> 
    group_by(run_year, StockID) |> 
    summarise(across(fram_escp, sum), .groups = "drop") 
  ,
  by = c("run_year", "StockID")
) |>
  mutate(
    fram_abnd = fram_lnd_yr_tot + fram_escp,
    fram_er_fsh = fram_lnd_yr_fsh / fram_abnd,
    fram_er_tot = fram_lnd_yr_tot / fram_abnd
  ) |> 
  select(run_year, everything())



er_rmis <- full_join(
  #analogous to FRAM mortality table
  rmis_rr |> 
    drop_na(estimated_number, StockID) |>
    mutate(
      StockID = if_else(StockID == 18, 20, StockID),
      FisheryID = if_else(FisheryID %in% fishery_ids_paired, FisheryID+1, as.double(FisheryID)),
      FisheryName = if_else(FisheryID %in% c(fishery_ids_paired, fishery_ids_paired+1),
                            str_sub(FisheryName, 1,8), FisheryName)
    ) |> 
    filter(
      age == 3, f_type != "escp",
      between(run_year, min(er_fram$run_year), max(er_fram$run_year)),
      StockID %in% stock_ids,
      FisheryID %in% fishery_ids
    ) |>
    group_by(run_year, StockID, f_type, FisheryID, FisheryName) |> 
    summarise(rmis_est_num_yr_fsh = sum(estimated_number), .groups = "drop") |> 
    left_join(
      samp_catch_coef_vals, 
      by = c("FisheryID", "run_year")
    ) |>
    mutate(rmis_est_num_yr_fsh = if_else(!is.na(coef), rmis_est_num_yr_fsh * coef, rmis_est_num_yr_fsh)) |> 
    group_by(run_year, StockID) |> 
    mutate(rmis_est_num_yr_tot = sum(rmis_est_num_yr_fsh)) |> 
    ungroup()
  ,
  #analogous to FRAM escapement table
  rmis_rr |> 
    drop_na(estimated_number, StockID) |> 
    mutate(StockID = if_else(StockID == 18, 20, StockID)) |> 
    filter(
      age == 3, f_type == "escp",
      between(run_year, min(er_fram$run_year), max(er_fram$run_year)),
      StockID %in% stock_ids
    ) |> 
    group_by(run_year, StockID) |> 
    summarise(rmis_escp = sum(estimated_number), .groups = "drop")
  ,
  by = c("run_year", "StockID")
  ) |> 
  mutate(
    run_year = as.integer(run_year),
    rmis_abnd = rmis_est_num_yr_tot + rmis_escp,
    rmis_er_fsh = rmis_est_num_yr_fsh / rmis_abnd,
    rmis_er_tot = rmis_est_num_yr_tot / rmis_abnd
  )


er_fram_rmis <- full_join(
  er_fram |> select(-StockLongName, -FisheryName, -coef),
  er_rmis |> select(-FisheryName, -coef),
  by = c("run_year", "StockID", "FisheryID")
) |> 
  left_join(fram$mort |> distinct(StockID, StockLongName), by = "StockID") |> 
  left_join(fram$mort |> distinct(FisheryID, FisheryName), by = "FisheryID") |> 
  mutate(
    fidnm = paste(FisheryID, FisheryName, sep = ":") |> fct_reorder(.x = FisheryID, .fun = min),
    sidnm = paste(StockID, StockLongName, sep = ":") |> fct_reorder(.x = StockID, .fun = min),
    d_yr_fsh = fram_lnd_yr_fsh - rmis_est_num_yr_fsh,
    d_yr_tot = fram_lnd_yr_tot - rmis_est_num_yr_tot,
    d_escp_fram_rmis = fram_escp - rmis_escp,
    d_er_fsh = fram_er_fsh - rmis_er_fsh,
    d_er_tot = fram_er_tot - rmis_er_tot
    ) 

```


# Results

```{r gt_total_er_annual}
er_fram_rmis |> 
  drop_na(d_er_tot) |>
  group_by(sidnm) |> 
  distinct(sidnm, run_year, fram_er_tot, rmis_er_tot, d_er_tot) |> #arrange(sidnm) |> print(n=50)
  ungroup() |>
  gt(groupname_col = "sidnm", rowname_col = "run_year") |> 
  #not working: gt::summary_rows(groups = "sidnm", fns = "mean") |> 
  fmt_percent(contains("_er"))
```

```{r gt_total_er_mean}
er_fram_rmis |> 
  drop_na(d_er_tot) |>
  group_by(sidnm) |> 
  distinct(sidnm, run_year, fram_er_tot, rmis_er_tot, d_er_tot) |> #arrange(sidnm) |> print(n=50)
  summarise(across(c(fram_er_tot, rmis_er_tot, d_er_tot), mean)) |> 
  gt() |> 
  fmt_percent(contains("_er"))
```



```{r}
min_fram_landed = 6

gg_dif <- map(
  set_names(levels(er_fram_rmis$sidnm)),
  function(s) {
    d <- er_fram_rmis |>
      filter(
        sidnm == s,
        fram_lnd_yr_fsh >= min_fram_landed
        #,run_year %in% c(2010:2014, 2017:2019)
      ) |> mutate(run_year = as.character(run_year))
    bind_rows(
      d,
      d |> group_by(sidnm, fidnm) |> 
        summarise(
          run_year = "mean error",
          d_er_fsh = mean(d_er_fsh, na.rm=T), .groups = "drop"),
      d |> group_by(sidnm, run_year) |> 
        summarise(
          fidnm = "0: annual mean error",
          d_er_fsh = mean(d_er_fsh, na.rm=T), .groups = "drop")
    ) |> 
      mutate(
        fidnm = factor(fidnm, levels = c(levels(er_fram_rmis$fidnm), "0: annual mean error")),
        shp = case_when(
          d_er_fsh > 0 ~ "FRAM > RMIS",
          d_er_fsh < 0 ~ "FRAM < RMIS",
          d_er_fsh == 0 ~ "FRAM = RMIS",
          is.na(rmis_er_fsh) ~ "FRAM-only",
          is.na(fram_er_fsh) ~ "RMIS-only"
        ),
        #sze = abs(d_er_fsh)
        sze = if_else(!is.na(d_er_fsh), abs(d_er_fsh), 0)
      ) |> 
      ggplot(aes(run_year, fidnm)) +
      geom_point(aes(shape = shp), size = 2) +
      geom_point(aes(shape = shp, size = sze, fill = d_er_fsh)) +
      scale_shape_manual(name = "", values = c("FRAM > RMIS" = 24, "FRAM < RMIS" = 25, "FRAM = RMIS" = 22, "FRAM-only" = 20, "RMIS-only" = 3)) +
      scale_size("ER diff. abs.", range = c(2.5, 10)) +
      #scale_fill_gradient2(name = NULL, low = "purple", mid = "lightgrey", high = "orange", midpoint = 0, na.value = "pink", aesthetics = c("color", "fill")) +
      scale_fill_fermenter(type = "div", palette = "PuOr", breaks = c(-0.1, -0.05, 0, 0.05, 0.1), limits = c(-.2, .2)) +
      guides(
        #size = guide_bins(range = c(2.5, 10)),
        fill = guide_colorbar(title="ER difference"),
        x = guide_axis("Run Year"),
        y = guide_axis("")) +
      facet_wrap(~sidnm, ncol = 2, scales = "free_y") +
      labs(
        title = "Differences in annual per-fishery pseudo-ER, FRAM - RMIS",
        subtitle = paste("Minimum annual landed catch in FRAM >=", min_fram_landed, "coho")
      )
  }
)


gg_dif$`20:Skagit River Hatchery Marked`


# pwalk(
#   list(paste0("gg_dif_", str_remove_all(names(gg_dif), "\\:| "), ".png"), gg_dif),
#   ggsave, path = dir_proj
# ) 

```

